import { randomUUID } from 'node:crypto';
import { Injectable } from '@nestjs/common';
import { auditActor } from '../audit/audit.service';
import type { RequestActor } from '../common/request-actor';
import { $Enums, Prisma } from '../generated/prisma/client';
import { PrismaService } from '../prisma/prisma.service';

/** The zone-authority scope of an Install creation (mirrors the read-surface `{role, zoneId}`). */
export interface InstallScope {
  role: string;
  /** The ZM's own zone; null for CSM / Operations Head (unrestricted, all zones). */
  zoneId: number | null;
}

/** One Install row to create — single-create body or one parsed CSV line. */
export interface InstallRowInput {
  vehicleNo: string;
  plantId: bigint;
  companyId: bigint;
  deviceType?: string | null;
  deviceId: bigint;
  simId?: string | null;
  targetDate?: Date | null;
  notes?: string | null;
}

/** Why a single row failed validation; surfaced per-row (with a line number) on CSV upload. */
export type InstallRowError =
  | 'VEHICLE_NOT_FOUND'
  | 'DEVICE_NOT_FOUND'
  | 'PLANT_NOT_FOUND'
  | 'COMPANY_NOT_FOUND'
  | 'VEHICLE_ALREADY_MAPPED'
  | 'DEVICE_ALREADY_MAPPED'
  | 'ZONE_FORBIDDEN';

/** JSON-safe view of a created Install Ticket (BigInt ids → strings). */
export interface InstallTicketView {
  ticketId: string;
  workType: $Enums.WorkType;
  status: $Enums.TicketStatus;
  deviceId: string;
  vehicleId: string | null;
  plantId: string;
  companyId: string;
  installTriggerSource: $Enums.InstallTriggerSource | null;
  createdBy: string | null;
  createdByRole: $Enums.Role | null;
  installBatchId: string | null;
}

export type CreateSingleOutcome =
  | { result: 'OK'; ticket: InstallTicketView }
  | { result: 'ERROR'; code: InstallRowError };

/** One CSV row's validation failure, keyed by the 1-based line number in the uploaded content. */
export interface CsvRowError {
  line: number;
  code: InstallRowError | 'MISSING_REQUIRED_FIELD' | 'INVALID_NUMBER';
  field?: string;
}

export type UploadCsvOutcome =
  | { result: 'OK'; batchId: string; ticketIds: string[] }
  | { result: 'INVALID'; errors: CsvRowError[] };

/** Resolved entity rows a validated install row needs to create its ticket. */
interface ResolvedRow {
  vehicleId: bigint;
  plantId: bigint;
  companyId: bigint;
  companyTier: $Enums.CompanyTier;
  deviceId: bigint;
}

/** The interactive-transaction client AuditService.withAudit hands to the work callback. */
type PrismaTx = Prisma.TransactionClient;

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** CSV header → InstallRowInput field. `vehicle_no, plant_id, company_id, device_type, device_id` are
 *  required; `sim_id, target_date, notes` are optional (Issue 33 / ADR-0011). */
const REQUIRED_COLUMNS = ['vehicle_no', 'plant_id', 'company_id', 'device_type', 'device_id'] as const;

/**
 * InstallService — manual Install Ticket creation (Issue 33, ADR-0011 / CONTEXT.md §11). Single-create
 * and CSV bulk upload, scoped to the creator's zone authority (ZM own zone / CSM scope / Operations
 * Head all zones). Each ticket records `created_by` + `created_by_role`, `install_trigger_source =
 * MANUAL_OPERATIONS`, an opening lifecycle event, and a full audit row — written in one transaction.
 * CSV upload is all-or-nothing: every row is validated first; if any row is bad, none are created and
 * the failures are returned with line numbers (no partial corruption of the backlog).
 */
@Injectable()
export class InstallService {
  constructor(private readonly prisma: PrismaService) {}

  /** Validate + create one Install Ticket (single-create UI). */
  async createSingle(
    row: InstallRowInput,
    scope: InstallScope,
    actor: RequestActor,
    now: Date = new Date(),
  ): Promise<CreateSingleOutcome> {
    const resolved = await this.validateRow(this.prisma, row, scope);
    if (resolved.result === 'ERROR') return resolved;

    // Manual transaction (not withAudit) because the audit row's entityId is the ticket id, which is
    // generated by the create — the same in-transaction create + event + audit as the CSV batch path.
    const ticket = await this.prisma.$transaction(async (tx) => {
      const created = await this.createTicket(tx, row, resolved.row, actor, now, null);
      await this.writeAudit(tx, actor, created.ticketId, {
        vehicleNo: row.vehicleNo,
        plantId: String(row.plantId),
      });
      return created;
    });
    return { result: 'OK', ticket: toView(ticket) };
  }

  /**
   * Validate + create a CSV batch. Parses the content, validates every row, and only if all rows pass
   * creates them in one transaction under a shared `install_batch_id`. Any failure returns the per-row
   * errors (with line numbers) and creates nothing.
   */
  async uploadCsv(
    csv: string,
    scope: InstallScope,
    actor: RequestActor,
    now: Date = new Date(),
  ): Promise<UploadCsvOutcome> {
    const parsed = parseCsv(csv);
    if (parsed.result === 'INVALID') return parsed;

    const errors: CsvRowError[] = [];
    const resolvedRows: { row: InstallRowInput; resolved: ResolvedRow }[] = [];
    for (const { row, line } of parsed.rows) {
      const outcome = await this.validateRow(this.prisma, row, scope);
      if (outcome.result === 'ERROR') {
        errors.push({ line, code: outcome.code });
      } else {
        resolvedRows.push({ row, resolved: outcome.row });
      }
    }
    if (errors.length > 0) return { result: 'INVALID', errors };

    const batchId = randomUUID();
    const ticketIds = await this.prisma.$transaction(async (tx) => {
      const ids: string[] = [];
      for (const { row, resolved } of resolvedRows) {
        const ticket = await this.createTicket(tx, row, resolved, actor, now, batchId);
        ids.push(ticket.ticketId);
        await this.writeAudit(tx, actor, ticket.ticketId, {
          vehicleNo: row.vehicleNo,
          plantId: String(row.plantId),
          installBatchId: batchId,
        });
      }
      return ids;
    });
    return { result: 'OK', batchId, ticketIds };
  }

  /** Per-row validation (existence + active-mapping + zone authority); resolves the rows needed to create. */
  private async validateRow(
    db: PrismaService | PrismaTx,
    row: InstallRowInput,
    scope: InstallScope,
  ): Promise<{ result: 'OK'; row: ResolvedRow } | { result: 'ERROR'; code: InstallRowError }> {
    const vehicle = await db.vehicle.findUnique({ where: { vehicleNo: row.vehicleNo } });
    if (!vehicle) return { result: 'ERROR', code: 'VEHICLE_NOT_FOUND' };

    const device = await db.device.findUnique({ where: { deviceId: row.deviceId } });
    if (!device) return { result: 'ERROR', code: 'DEVICE_NOT_FOUND' };

    const plant = await db.plant.findUnique({ where: { plantId: row.plantId } });
    if (!plant) return { result: 'ERROR', code: 'PLANT_NOT_FOUND' };

    const company = await db.company.findUnique({ where: { companyId: row.companyId } });
    if (!company) return { result: 'ERROR', code: 'COMPANY_NOT_FOUND' };

    // No active Device mapping: the target vehicle must not already carry a fitted device, and the
    // device being installed must not already be active on some vehicle (it must be free stock).
    const vehicleHasDevice = await db.device.findFirst({
      where: { currentVehicleId: vehicle.vehicleId },
      select: { deviceId: true },
    });
    if (vehicleHasDevice) return { result: 'ERROR', code: 'VEHICLE_ALREADY_MAPPED' };
    if (device.currentVehicleId != null) return { result: 'ERROR', code: 'DEVICE_ALREADY_MAPPED' };

    // Zone authority: a ZM is confined to its own zone; CSM / Operations Head are unrestricted.
    if (scope.role === 'ZONAL_MANAGER' && scope.zoneId != null && Number(plant.zoneId) !== scope.zoneId) {
      return { result: 'ERROR', code: 'ZONE_FORBIDDEN' };
    }

    return {
      result: 'OK',
      row: {
        vehicleId: vehicle.vehicleId,
        plantId: plant.plantId,
        companyId: company.companyId,
        companyTier: company.companyTier,
        deviceId: device.deviceId,
      },
    };
  }

  /** Creates the Install Ticket row + its opening lifecycle event inside the given transaction. */
  private async createTicket(
    tx: PrismaTx,
    row: InstallRowInput,
    resolved: ResolvedRow,
    actor: RequestActor,
    now: Date,
    batchId: string | null,
  ): Promise<{
    ticketId: string;
    workType: $Enums.WorkType;
    status: $Enums.TicketStatus;
    deviceId: bigint;
    vehicleId: bigint | null;
    plantId: bigint;
    companyId: bigint;
    installTriggerSource: $Enums.InstallTriggerSource | null;
    createdBy: string | null;
    createdByRole: $Enums.Role | null;
    installBatchId: string | null;
  }> {
    const ticket = await tx.ticket.create({
      data: {
        workType: 'INSTALL',
        status: 'REQUESTED',
        deviceId: resolved.deviceId,
        vehicleId: resolved.vehicleId,
        plantId: resolved.plantId,
        companyId: resolved.companyId,
        companyTier: resolved.companyTier,
        lastStateChangedAt: now,
        installTriggerSource: 'MANUAL_OPERATIONS',
        createdBy: UUID_RE.test(actor.userId) ? actor.userId : null,
        createdByRole: actor.role as $Enums.Role,
        installSimId: row.simId ?? null,
        installTargetDate: row.targetDate ?? null,
        installNotes: row.notes ?? null,
        installBatchId: batchId,
      },
    });
    await tx.ticketEvent.create({
      data: { ticketId: ticket.ticketId, fromState: null, toState: 'REQUESTED', at: now },
    });
    return ticket;
  }

  /** Writes one INSTALL_TICKET_CREATED audit row inside a CSV-batch transaction (mirrors withAudit). */
  private async writeAudit(
    tx: PrismaTx,
    actor: RequestActor,
    ticketId: string,
    metadata: Prisma.InputJsonValue,
  ): Promise<void> {
    const fields = auditActor(actor);
    await tx.auditLog.create({
      data: {
        actorId: fields.actorId,
        actorRole: fields.actorRole,
        actedAsRole: fields.actedAsRole ?? null,
        actingZone: fields.actingZone != null ? BigInt(fields.actingZone) : null,
        action: 'INSTALL_TICKET_CREATED',
        entityType: 'tickets',
        entityId: ticketId,
        metadata,
      },
    });
  }
}

function toView(ticket: {
  ticketId: string;
  workType: $Enums.WorkType;
  status: $Enums.TicketStatus;
  deviceId: bigint;
  vehicleId: bigint | null;
  plantId: bigint;
  companyId: bigint;
  installTriggerSource: $Enums.InstallTriggerSource | null;
  createdBy: string | null;
  createdByRole: $Enums.Role | null;
  installBatchId: string | null;
}): InstallTicketView {
  return {
    ticketId: ticket.ticketId,
    workType: ticket.workType,
    status: ticket.status,
    deviceId: String(ticket.deviceId),
    vehicleId: ticket.vehicleId != null ? String(ticket.vehicleId) : null,
    plantId: String(ticket.plantId),
    companyId: String(ticket.companyId),
    installTriggerSource: ticket.installTriggerSource,
    createdBy: ticket.createdBy,
    createdByRole: ticket.createdByRole,
    installBatchId: ticket.installBatchId,
  };
}

/** Parsed CSV → header-mapped rows with their source line numbers, or a structural error list. */
function parseCsv(
  csv: string,
):
  | { result: 'OK'; rows: { row: InstallRowInput; line: number }[] }
  | { result: 'INVALID'; errors: CsvRowError[] } {
  const lines = csv.split(/\r?\n/);
  // Find the header (first non-blank line) and remember its 1-based position for downstream numbering.
  let headerLine = -1;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].trim() !== '') {
      headerLine = i;
      break;
    }
  }
  if (headerLine === -1) return { result: 'INVALID', errors: [{ line: 1, code: 'MISSING_REQUIRED_FIELD' }] };

  const header = lines[headerLine].split(',').map((h) => h.trim().toLowerCase());
  const missingCol = REQUIRED_COLUMNS.find((c) => !header.includes(c));
  if (missingCol) {
    return { result: 'INVALID', errors: [{ line: headerLine + 1, code: 'MISSING_REQUIRED_FIELD', field: missingCol }] };
  }

  const idx = (name: string) => header.indexOf(name);
  const rows: { row: InstallRowInput; line: number }[] = [];
  const errors: CsvRowError[] = [];
  for (let i = headerLine + 1; i < lines.length; i++) {
    if (lines[i].trim() === '') continue; // skip blank lines
    const lineNo = i + 1; // 1-based, as a person reading the file sees it
    const cells = lines[i].split(',').map((c) => c.trim());
    const get = (name: string): string => {
      const j = idx(name);
      return j >= 0 && j < cells.length ? cells[j] : '';
    };

    const vehicleNo = get('vehicle_no');
    const plantRaw = get('plant_id');
    const companyRaw = get('company_id');
    const deviceRaw = get('device_id');
    if (!vehicleNo || !plantRaw || !companyRaw || !deviceRaw) {
      errors.push({ line: lineNo, code: 'MISSING_REQUIRED_FIELD' });
      continue;
    }
    const plantId = parseBigInt(plantRaw);
    const companyId = parseBigInt(companyRaw);
    const deviceId = parseBigInt(deviceRaw);
    if (plantId === null || companyId === null || deviceId === null) {
      errors.push({ line: lineNo, code: 'INVALID_NUMBER' });
      continue;
    }

    const targetRaw = get('target_date');
    let targetDate: Date | null = null;
    if (targetRaw) {
      const d = new Date(targetRaw);
      if (Number.isNaN(d.getTime())) {
        errors.push({ line: lineNo, code: 'INVALID_NUMBER', field: 'target_date' });
        continue;
      }
      targetDate = d;
    }

    rows.push({
      line: lineNo,
      row: {
        vehicleNo,
        plantId,
        companyId,
        deviceId,
        deviceType: get('device_type') || null,
        simId: get('sim_id') || null,
        targetDate,
        notes: get('notes') || null,
      },
    });
  }

  if (errors.length > 0) return { result: 'INVALID', errors };
  return { result: 'OK', rows };
}

function parseBigInt(raw: string): bigint | null {
  if (!/^\d+$/.test(raw)) return null;
  try {
    return BigInt(raw);
  } catch {
    return null;
  }
}
